#!/bin/bash

printf "Full path of the drive to be imaged: "
read if
of="image_$(date +%Y%m%d%H%M%S).dd"

printf "Type IMAGE-THIS-DRIVE to start the image on $if."
read confirm

echo "Output filename: ~/$of"
if [[ $confirm == "IMAGE-THIS-DRIVE" ]]; then

	dd if=$if of=~/$of bs=512 conv=noerror,sync

else 
	echo "Drive image aborted."

fi
